In [1]:
import numpy as np
from src.commons import render_maze, create_maze
import cv2

In [2]:
(0,0)+(0,1)

(0, 0, 0, 1)

In [25]:
np.where(np.array([[2,3],[5,6],[8,9]]) == np.max(np.array([[2,3],[5,6],[8,9]])))

(array([2], dtype=int64), array([1], dtype=int64))

In [3]:
def Djistra(maze, start, end):
    current_node=start
    
    cost=np.zeros_like(maze, dtype=int)
    visited_nodes=[start]
    reference_nodes=[start]

    dimX=maze.shape[0]
    dimY=maze.shape[1]

    directions=[(0,1),(1,0),(0,-1),(-1,0)]

    while(current_node != end):
        next_node=current_node
        next_cost=0
        for dx, dy in directions:
            nx,ny=current_node[0]+dx, current_node[1]+dy
            if nx >= 0 and nx < dimX and ny >= 0 and ny < dimY and maze[nx,ny] != "W":
                if (nx,ny) not in visited_nodes:
                    visited_nodes.append((nx,ny))
                    reference_nodes.append(current_node)
                    cost[nx,ny]=cost[current_node]+1

                else:
                    if cost[nx,ny] > cost[current_node]+1:
                        cost[nx,ny]=cost[current_node]+1
                        reference_nodes[visited_nodes.index((nx,ny))]=current_node
                
                # get the node with the highest cost that has not been visited
                highest=np.where([[2,3],[5,6],[8,9]]== max
                while x in highest:
                    if highest in visited_nodes:
                        return false
                si no elgge este
                
        
        print("-----------------------------------")
        print(cost)
        print("NEXT NODE:",next_node, "--------------------------")

        current_node=next_node
    return visited_nodes, reference_nodes

        

                
                    

In [17]:
maze=create_maze(20,20)
maze[-2,-2]="G"
maze

array([['0', '0', '0', 'W', '0', '0', '0', '0', '0', '0', '0', '0', '0',
        'W', '0', '0', '0', '0', '0', 'W'],
       ['W', 'W', '0', 'W', 'W', 'W', 'W', 'W', '0', 'W', 'W', 'W', '0',
        'W', 'W', 'W', 'W', 'W', '0', 'W'],
       ['0', 'W', '0', '0', '0', '0', '0', 'W', '0', 'W', '0', '0', '0',
        'W', '0', '0', '0', '0', '0', 'W'],
       ['0', 'W', 'W', 'W', 'W', 'W', '0', 'W', '0', 'W', '0', 'W', 'W',
        'W', '0', 'W', 'W', 'W', '0', 'W'],
       ['0', '0', '0', 'W', '0', '0', '0', 'W', '0', 'W', '0', 'W', '0',
        '0', '0', '0', '0', 'W', '0', 'W'],
       ['0', 'W', '0', 'W', '0', 'W', 'W', 'W', '0', 'W', '0', 'W', 'W',
        'W', '0', 'W', '0', 'W', 'W', 'W'],
       ['0', 'W', '0', '0', '0', 'W', '0', '0', '0', 'W', '0', '0', '0',
        'W', '0', 'W', '0', '0', '0', 'W'],
       ['0', 'W', 'W', 'W', 'W', 'W', '0', 'W', '0', 'W', 'W', 'W', '0',
        'W', 'W', 'W', 'W', 'W', '0', 'W'],
       ['0', 'W', '0', '0', '0', '0', '0', 'W', '0', 'W', '0', '

In [18]:
maze

array([['0', '0', '0', 'W', '0', '0', '0', '0', '0', '0', '0', '0', '0',
        'W', '0', '0', '0', '0', '0', 'W'],
       ['W', 'W', '0', 'W', 'W', 'W', 'W', 'W', '0', 'W', 'W', 'W', '0',
        'W', 'W', 'W', 'W', 'W', '0', 'W'],
       ['0', 'W', '0', '0', '0', '0', '0', 'W', '0', 'W', '0', '0', '0',
        'W', '0', '0', '0', '0', '0', 'W'],
       ['0', 'W', 'W', 'W', 'W', 'W', '0', 'W', '0', 'W', '0', 'W', 'W',
        'W', '0', 'W', 'W', 'W', '0', 'W'],
       ['0', '0', '0', 'W', '0', '0', '0', 'W', '0', 'W', '0', 'W', '0',
        '0', '0', '0', '0', 'W', '0', 'W'],
       ['0', 'W', '0', 'W', '0', 'W', 'W', 'W', '0', 'W', '0', 'W', 'W',
        'W', '0', 'W', '0', 'W', 'W', 'W'],
       ['0', 'W', '0', '0', '0', 'W', '0', '0', '0', 'W', '0', '0', '0',
        'W', '0', 'W', '0', '0', '0', 'W'],
       ['0', 'W', 'W', 'W', 'W', 'W', '0', 'W', '0', 'W', 'W', 'W', '0',
        'W', 'W', 'W', 'W', 'W', '0', 'W'],
       ['0', 'W', '0', '0', '0', '0', '0', 'W', '0', 'W', '0', '

In [20]:
Djistra(maze, (0,0), (18,18))

-----------------------------------
[[0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
NEXT NODE: (0, 1) --------------------------
-----------------------------------
[[0 1 2 0 0 0 0 0 0 0 

KeyboardInterrupt: 

In [7]:
cv2.imshow("game",render_maze(maze))
cv2.waitKey(0)

KeyboardInterrupt: 